name: CI

on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - "**/.md"
  pull_request:
    branches:
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build custom image
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        recipe:
          # !! Add your recipes here
          - recipe-gnome.yml
          - recipe-hyprland.yml
          - recipe-gnome-intel.yml
          - recipe-hyprland-intel.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.9.1
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          skip_checkout: true # we already checked out the repository

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: false

  iso:
    name: Build ISO
    runs-on: ubuntu-24.04
    needs: build
    if: github.event_name != 'pull_request'

    strategy:
      matrix:
        name:
          - lightblue
          - lightblue-hyprland
          - lightblue-intel
          - lightblue-hyprland-intel

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build ISO
        run: |
          bash <(curl -s https://raw.githubusercontent.com/blue-build/cli/main/install.sh)
          bluebuild generate-iso --iso-name ${{ matrix.name }}.iso image ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}

      - name: Upload disk image to Job Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.name }}.iso
          name: ${{ matrix.name }}
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
          overwrite: true
